on:
  pull_request:
    branches:
      - 'main'

jobs:
  android-alpha-distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Set version
        id: set_version
        run: |
           pr_title="${{ github.event.pull_request.title }}"
           IFS=';'
           android_version=$(echo "$pr_title" | grep -o -E -i 'android:v[0-9]+\.[0-9]+\.[0-9]+' | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')

          if [ -n "$android_version" ]; then
            echo "version=$android_version" >> $GITHUB_OUTPUT
          else
            echo "The PR name does not contain a valid Android version"
            exit 1
          fi
